# Generated by Django 3.1.5 on 2021-01-17 07:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('post', '0003_auto_20210117_1551'),
    ]

    operations = [
        migrations.AlterField(
            model_name='post',
            name='imgurl',
            field=models.CharField(blank=True, max_length=500, null=True),
        ),
    ]
