# Generated by Django 3.1.5 on 2021-01-17 10:11

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('post', '0006_post_mimage'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='post',
            name='imgurl',
        ),
    ]
