# Generated by Django 3.1.5 on 2021-01-17 10:19

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('post', '0007_remove_post_imgurl'),
    ]

    operations = [
        migrations.RenameField(
            model_name='post',
            old_name='mimage',
            new_name='imgurl',
        ),
    ]
