# Generated by Django 3.1.5 on 2021-01-18 01:35

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('post', '0010_post_owner'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='post',
            name='owner',
        ),
    ]
