# Generated by Django 3.1.5 on 2021-01-19 01:32

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('post', '0013_auto_20210119_1031'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='comment',
            name='comment_update_date',
        ),
    ]
