# Generated by Django 3.1.5 on 2021-01-19 07:57

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('post', '0015_auto_20210119_1645'),
    ]

    operations = [
        migrations.AddField(
            model_name='postimage',
            name='parentt',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='replyy', to='post.postimage'),
        ),
    ]
