# Generated by Django 3.1.5 on 2021-01-20 05:56

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('post', '0017_auto_20210119_1706'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='postimage',
            name='parentt',
        ),
        migrations.AddField(
            model_name='postimage',
            name='parent',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='reply', to='post.postimage'),
        ),
    ]
