# Generated by Django 3.1.5 on 2021-01-20 06:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('post', '0020_auto_20210120_1502'),
    ]

    operations = [
        migrations.AddField(
            model_name='comment',
            name='cstar',
            field=models.PositiveSmallIntegerField(default=5),
        ),
    ]
